version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo "No pre-build steps needed"
    build:
      commands:
        - echo "Build complete"
  artifacts:
    baseDirectory: frontend
    files:
      - index.html
      - style.css
      - script.js
  cache:
    paths: []
